import Head from "next/head";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import TodoList from "@/components/TodoList";
import { useEffect } from "react";
import LoginPage from "./login";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();
  useEffect(() => {
    if (session) {
      const updateUserInfo = async () => {
        const { user } = session;
        const { data, error } = await supabase.from("users").upsert({
          id: user.id, // これはSupabaseによって自動的に作成されたユーザーID
          email: user.email, // サインイン時に入力されたメールアドレス
        });

        if (error) {
          console.error("Error updating user info:", error);
        }
      };
      updateUserInfo();
    }
  }, [session, supabase]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-gray-200">
        {!session ? (
          <LoginPage />
        ) : (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: "auto" }}
          >
            <TodoList session={session} />
          </div>
        )}
      </div>
    </>
  );
}
