import Head from "next/head";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import TodoList from "@/components/TodoList";
import { useEffect } from "react";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();
  useEffect(() => {
    if (session) {
      // ここでユーザー情報をusersテーブルに保存します
      const updateUserInfo = async () => {
        const { user } = session;
        const { data, error } = await supabase.from("users").upsert(
          {
            id: user.id, // これはSupabaseによって自動的に作成されたユーザーIDです
            email: user.email, // サインイン時に入力されたメールアドレス
            // nameや他のフィールドを追加する場合はここに追加します
          },
          {
            returning: "minimal", // 応答としてデータが返されないようにする（パフォーマンスの向上）
          }
        );

        if (error) {
          console.error("Error updating user info:", error);
        }
      };

      updateUserInfo();
    }
  }, [session, supabase]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-gray-200">
        {!session ? (
          <div className="min-w-full min-h-screen flex items-center justify-center">
            <div className="w-full h-full flex justify-center items-center p-4">
              <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                <span className="font-sans text-4xl text-center pb-2 mb-1 border-b mx-4 align-center">
                  Login
                </span>
                <Auth
                  supabaseClient={supabase}
                  appearance={{ theme: ThemeSupa }}
                  theme="dark"
                />
              </div>
            </div>
          </div>
        ) : (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: "auto" }}
          >
            <TodoList session={session} />
          </div>
        )}
      </div>
    </>
  );
}
